---
title: "Figure5"
author: "Ritika"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, comment = "##", prompt = TRUE, tidy = TRUE, tidy.opts = list(width.cutoff = 75), fig.path = "/Users/ritikasibal/Desktop/W24/Research/OntogenyOfLocomotion/Final Code/Figure5 Images/")
```

## Load all the necessary libraries

``` {r librarys, echo = T, results = 'hide', message=FALSE, warnings=FALSE}
library(tidyverse)
library(magrittr) # needs to be run every time you start R and want to use %>%
library(dplyr)  
library(vegan)
library(readxl)
library(effects)
library(ggeffects)
library(gridExtra)
library(ggstance)
library(MuMIn)
library(DHARMa)
library(sjPlot)
library(glmmTMB)
library(lme4)
library(ggpubr)
library(gridExtra)
library(entropy)
library(ggtext)
library(reshape2)
```

## Postprocess Data

This is run everytime. Make sure to change this path to your local directory

``` {r postprocessing_data}
load_in_data_post <- function(path, adult){
  #path = "~/Desktop/W24/Research/OntogenyOfLocomotion/Ritika Excel Files/parsed-all.xlsx"
  d <- read_xlsx(path ,sheet = 1, guess_max = 1048576)
  
  d_cols <- read_xlsx(path,sheet = 2, guess_max = 1048576)
  d<- subset(d, `Minutes awake` >= 360)
  # Make NAs to Zeros
  d <- imputeTS::na_replace(d)
  # Make everything numeric
  d[8:ncol(d)] <- sapply(d[8:ncol(d)],as.numeric)
  
  if (adult){
      df <-d[c("Follow Number", "Name", "Minutes awake", "Age", "Mother Class")]
      df$Age <- tolower(df$Age)
  } else {
      df <-d[c("Follow Number", "Name", "Minutes awake", "Age","Age class lookup", "Age Class II lookup")]
      df$`Age class lookup` <- tolower(df$`Age class lookup`)
       df$`Age Class II lookup` <- tolower(df$`Age Class II lookup`)
  }

  names(d) <- sub("PB ", "", names(d))
  names(d) <- sub(" TotalMinute", "", names(d))
  names(d) <- sub(" TotalMinutes", "", names(d))

  # Drop all the NAs
  df<-df[!is.na(df$`Follow Number`), ]
  df<-df[!is.na(df$Name), ]
  df<-df[!is.na(df$`Minutes awake`), ]
  
  # Do all the non-pooled
  for (col_name in d_cols$Nonpooled) {
    index <- grepl(col_name, colnames(d))
    df <- cbind(df, d[index])
  }
  
  # Do all the pooled categories
  for (idx in 1:length(na.omit(d_cols$Pooled))) {
    cat <- strsplit(d_cols$Categories[idx], "")
    for (jdx in 1:length(cat[[1]])) {
      string = paste(d_cols$Pooled[idx], cat[[1]][jdx], sep = "")
      index <- grepl(string, colnames(d))
      if (jdx == 1){
        pooled_min <- d[index]
      } else {
        pooled_min <- pooled_min + d[index]
      }
    }
    colnames(pooled_min)[1] <- paste(d_cols$Pooled[idx], d_cols$Categories[idx], sep="")
    # divide so that the proportion of the day still makes sense
    #df <- cbind(df, pooled_min/length(cat[[1]]))
    df <- cbind(df, pooled_min)
  }
  
  # Normalize Data
  if(adult){
      df[,6:ncol(df)] <- df[,6:ncol(df)]/df$`Minutes awake`
      df <-df[rowSums(df[, 6:ncol(df)] > 1) == 0, ]
  } else{
      df[,7:ncol(df)] <- df[,7:ncol(df)]/df$`Minutes awake`
      df <-df[rowSums(df[, 7:ncol(df)] > 1) == 0, ]
  }
  
  if (adult) {
    df <- df %>% mutate(Age = case_when(
      # mothers with old children
      grepl('\\badult female\\b', Age) & (grepl('\\bOver\\b', `Mother Class`) |  grepl('\\<JUV\\>', `Mother Class`)) ~ 7)) # Over 4 years
    colnames(df)[5] <- "Age class lookup"
  } else{
    #df$Age = as.numeric(df$Age)
    df <- df %>% mutate(Age = case_when(
      Age >= 0  & Age < 2 ~ '1',
      Age >= 2  & Age < 4 ~ '2',
      Age >= 4  & Age < 6 ~ '3',
      Age >= 6  & Age < 8 ~ '4',
      Age >= 8  & Age < 10 ~ '5',
      Age >= 10  & Age < 12 ~ '6',
      # non mothers
      Age >= 12 & grepl('\\badult female\\b', `Age class lookup`) & grepl('\\bnon-mother\\b', `Age Class II lookup`) ~ '7',
      Age >= 12 & grepl ('\\bflanged male\\b', `Age class lookup`) ~ '7'))
    df <- df %>% select(-contains('Age Class II lookup'))
  }

  df<-df[!is.na(df$Age), ]
  df <- df %>% replace(is.na(.), 0)
  
  return(df)
}

d_juv <- load_in_data_post("~/Desktop/W24/Research/OntogenyOfLocomotion/Ritika Excel Files/parsed-all.xlsx", adult=FALSE)

d_adult <- load_in_data_post("~/Desktop/W24/Research/OntogenyOfLocomotion/Ritika Excel Files/parsed-mother-infant.xlsx", adult=TRUE)

d <- rbind(d_juv, d_adult)
d <- d %>% distinct(`Follow Number`, .keep_all = TRUE)

rm(d_juv, d_adult)

#library("writexl")
#write_xlsx(d,"~/Desktop/W24/Research/OntogenyOfLocomotion/all-juve-adult_female_.xlsx")
```

## Seperate data into sex

``` {r map_to_sex}
sex_d <- d %>% mutate(`Age class lookup` = case_when(
    grepl('\\bfemale\\b', `Age class lookup`) ~ 'F',
    grepl('\\bmale\\b', `Age class lookup`) ~ 'M'
    ))
d_dict <- sex_d[, c("Name", "Age class lookup")]
d_dict <- unique(d_dict)
d_dict<-d_dict[!is.na(d_dict$`Age class lookup`), ]
names(d_dict)[names(d_dict) == "Age class lookup"] <- "Sex"

dict <- read_xlsx("/Users/ritikasibal/Desktop/W24/Research/OntogenyOfLocomotion/Ritika Excel Files/IndividualSex.xlsx" ,sheet = 1, guess_max = 1048576)
dict <- dict %>% select(-contains('Entry Date'))

sex_dict <- rbind(dict, d_dict)
sex_dict$Name <- tolower(sex_dict$Name)

d['Sex'] = NA
for(row in 1:nrow(d)){
  j = tolower(d$Name[row])
  d$Sex[row] = (subset(sex_dict, Name == j))$Sex[1]
}
d <- d %>% replace(is.na(.), 0)
```

## Box plot with significance

``` {r boxplot_significance}
female_d <- d[d$Sex == "F",1:ncol(d)-1]
male_d <- d[d$Sex == "M",1:ncol(d)-1]

female_d <- female_d %>%
  pivot_longer(cols = 6:ncol(female_d),
               names_to = "PositionalBehavior",
               values_to = "Value")

male_d <- male_d %>%
  pivot_longer(cols = 6:ncol(male_d),
               names_to = "PositionalBehavior",
               values_to = "Value")

female_d$Sex <- 'Female'
male_d$Sex <- 'Male'
data <- rbind(female_d, male_d)

plot_boxplot <- function(data){
  data$PositionalBehavior <- factor(data$PositionalBehavior, levels = unique(data$PositionalBehavior))
  
  data <- data %>%
    group_by(PositionalBehavior) %>%
    filter(any(Value[Sex == "Female"] != 0) & any(Value[Sex == "Male"] != 0))

  data_filtered = subset(data, Value > 0)

  p_values <- data_filtered %>%
    group_by(PositionalBehavior, Age) %>%
    filter(n_distinct(Sex) == 2) %>%  # Ensure both genders are present
    filter(sum(Sex == "Female") >= 2 & sum(Sex == "Male") >= 2) %>%  # Ensure at least 2 observations per group
    summarize(p_value = t.test(Value ~ Sex)$p.value) %>%
    ungroup()
  
  # Bonferoni calculations
  unique_pvals <- length(unique(p_values$PositionalBehavior))
  num_comparisons <- unique_pvals * (unique_pvals - 1) / 2
  bonferoni_significance_level <- 0.05 / num_comparisons
  
  # Filter to keep only significant comparisons
  significant_data <- p_values %>%
    filter(p_value < bonferoni_significance_level) %>%
    inner_join(data_filtered, by = c("PositionalBehavior", "Age"))
  unique_values <- unique(significant_data$PositionalBehavior)

  ggplot(significant_data, aes(x = Sex, y = Value, fill = Sex)) +
    geom_boxplot(lwd = 0.1, outliers = FALSE) +
    facet_grid(PositionalBehavior ~ Age, switch = "both", scales = 'free') +
    #geom_text(data = unique_significant_data, 
            #aes(label = ifelse(p_value < bonferoni_significance_level, sprintf("***", p_value), "")), 
            #position = position_dodge(width=0.5), 
            #size = 3) +
    #stat_compare_means(data=significant_data, method = "t.test", label = "p.signif", hide.ns = TRUE, position=position_nudge(x=0.3, y = -0.4)) +
    scale_y_continuous(labels = function(x) format(x, digits = 1)) +
    theme_classic() +
    scale_fill_manual(values = c("#e6e6fa", "#d0efff")) +
    labs(title = "Comparison of Positional Behaviors by Age and Sex", x = "Age") +
    theme(
      strip.text.y.left = element_text(angle = 0),
      strip.background = element_blank(),
      axis.text.y = element_text(angle = 0, hjust = 0.5),
      axis.text.x = element_text(angle = 45, hjust = 1),
      axis.ticks.y = element_blank(),
      axis.line.y = element_blank(),
      axis.title.y = element_blank(),
      panel.spacing.y = unit(0.4, "cm")
    )
  
}
plot_boxplot(data)
```